In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import copy

In [2]:
import warnings
warnings.filterwarnings(action='ignore')

In [3]:
# 연관어 19년도, 20년도
Associate_19 = pd.read_csv('/Users/jaeyoungcho/Desktop/2020 금융 빅데이터 챌린지-공모전데이터/데이터/다음소프트/연관어_2019.csv',sep = ',',encoding='CP949')
Associate_20 = pd.read_csv('/Users/jaeyoungcho/Desktop/2020 금융 빅데이터 챌린지-공모전데이터/데이터/다음소프트/연관어_2020.csv',sep = ',',encoding='CP949')

# Original_19, Original_20 리스트안에 인덱스 0,1,2 순으로 5월, 6월, 7월 데이터 순서대로 매핑
Original_19 = []
Original_20 = []
for i in range(5,8):
    temp_19 = pd.read_csv('/Users/jaeyoungcho/Desktop/2020 금융 빅데이터 챌린지-공모전데이터/데이터/다음소프트/원문정보_20190{}.csv'.format(i),sep = ',',encoding = 'CP949')
    temp_20 = pd.read_csv('/Users/jaeyoungcho/Desktop/2020 금융 빅데이터 챌린지-공모전데이터/데이터/다음소프트/원문정보_20200{}.csv'.format(i),sep = ',',encoding = 'CP949')
    Original_19.append(temp_19)
    Original_20.append(temp_20)

# KeyWord_19, KeyWord_20
Keyword_19 = pd.read_csv('/Users/jaeyoungcho/Desktop/2020 금융 빅데이터 챌린지-공모전데이터/데이터/다음소프트/키워드버즈추이_2019.csv',sep = ',',encoding = 'CP949')
Keyword_20 = pd.read_csv('/Users/jaeyoungcho/Desktop/2020 금융 빅데이터 챌린지-공모전데이터/데이터/다음소프트/키워드버즈추이_2020.csv',sep = ',',encoding = 'CP949')

# Text 키워드셋
text_keyword = pd.read_csv('/Users/jaeyoungcho/Desktop/2020 금융 빅데이터 챌린지-공모전데이터/데이터/다음소프트/키워드셋.txt',sep = '\n',encoding = 'CP949')

# 연관어

In [4]:
for i in text_keyword['코로나19'].tolist():
    if i not in Associate_19['키워드'].unique().tolist():
        print(i)

코로나확진자
사회적거리두기
2차재난지원금
고위험시설
뉴딜펀드

In [5]:
Associate_19['연관어']

0          농림부
1          코로나
2           백신
3           접종
4           hp
          ...
190190    기자회견
190191      정책
190192     트럼프
190193     민주당
190194     대통령
Name: 연관어, Length: 190195, dtype: object

In [6]:
Associate_20

          키워드      기준일자      연관어  문서빈도수        채널
0       코로나19  20200501      코로나   4138   ko.news
1       코로나19  20200501     바이러스   1636   ko.news
2       코로나19  20200501  코로나바이러스   1481   ko.news
3       코로나19  20200501      감염증   1437   ko.news
4       코로나19  20200501       서울   1415   ko.news
...       ...       ...      ...    ...       ...
498781   그린뉴딜  20200731       미국      2  ko.total
498782   그린뉴딜  20200731      위원회      2  ko.total
498783   그린뉴딜  20200731       한국      2  ko.total
498784   그린뉴딜  20200731       소통      2  ko.total
498785   그린뉴딜  20200731       서울      2  ko.total

[498786 rows x 5 columns]

# Original

In [7]:
Original_19[2]

,키워드,기준일자,채널,제목,작성자,작성일시,URL
0,코로나19,20190726,ko.blog,Ep.6 도전! 셀프촬영 (~50days),NaN,20190726175717,http://blog.naver.com/dmswlsl15/221596447448
1,코로나19,20190705,ko.blog,쉐라톤 디큐브시티 호텔 뷔페 피스트,NaN,20190705220147,http://blog.naver.com/1020minhee/221578745647
2,코로나백신,20190727,ko.blog,# 하하랜독&캣 # 청북장모치와와,NaN,20190727001526,http://blog.naver.com/aa7848/221596740469
3,코로나백신,20190725,ko.blog,아주 작은 하얀 솜사탕 ! 포메라니안 분양소식 전합니다~!,NaN,20190725184221,http://blog.naver.com/goodpet114/221595442024
4,코로나백신,20190720,ko.blog,경기광주애견샵 20년 전통 이유가있지,NaN,20190720201905,http://blog.naver.com/tmxkdlfehr9166/221590845178
...,...,...,...,...,...,...,...
27543,뉴딜,20190701,ko.blog,"#신아일보 7월 1일자 9(전국)면, 15-16(대전충청)면 배달입니다.",NaN,20190701003255,http://blog.naver.com/dragon48/221574563391
27544,뉴딜,20190701,ko.blog,"김병수 울릉군수, 민선7기 출범1주년 기자간담회 개최",NaN,20190701001658,http://blog.naver.com/dsb1009/221574554061
27545,뉴딜,20190701,ko.blog,"김병수 울릉군수, 민선7기 출범1주년 기자간담회 개최",NaN,20190701001641,http://blog.naver.com/dsb1009/221574553847
27546,그린뉴딜,20190731,ko.news,"""중산층 의보 부담 낮출것"" 샌더스·워런 먼저 웃었다",매일경제,20190731000000,https://news.naver.com/main/read.nhn?mode=LPOD...
27547,그린뉴딜,20190716,ko.news,"정의당의 대안정당 도전, 이번엔 제대로 성공할까",노컷뉴스,20190716000000,https://news.naver.com/main/read.nhn?mode=LPOD...

# Keyword

In [8]:
Associate_19['키워드'].unique().tolist()

['코로나백신',
 '비대면',
 '마스크',
 '마스크스트랩',
 'kf94마스크',
 '손소독제',
 '소상공인',
 '피시방',
 '깜깜이',
 '뉴딜',
 '그린뉴딜']

In [9]:
Keyword_19['키워드'].unique().tolist()

['코로나19',
 '코로나확진자',
 '코로나백신',
 '사회적거리두기',
 '비대면',
 '2차재난지원금',
 '마스크',
 '마스크스트랩',
 'kf94마스크',
 '손소독제',
 '소상공인',
 '고위험시설',
 '피시방',
 '깜깜이',
 '뉴딜',
 '뉴딜펀드',
 '그린뉴딜']

In [10]:
Keyword_20

        키워드      기준일자  문서빈도수        채널
0     코로나19  20200501   4641   ko.news
1     코로나19  20200502   2205   ko.news
2     코로나19  20200503   3190   ko.news
3     코로나19  20200504   6677   ko.news
4     코로나19  20200505   4665   ko.news
...     ...       ...    ...       ...
7713   그린뉴딜  20200727     12  ko.total
7714   그린뉴딜  20200728     22  ko.total
7715   그린뉴딜  20200729     10  ko.total
7716   그린뉴딜  20200730      8  ko.total
7717   그린뉴딜  20200731     11  ko.total

[7718 rows x 4 columns]